version: '3.8'

services:
  # بوابة الوصول الخارجية
  range-gateway:
    image: nginx:alpine
    container_name: range-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - frontend-net
      - isolated-range
    depends_on:
      - student-node
      - doctor-node

  # عقدة الطالب - كالي لينكس (معزولة عن الإنترنت)
  student-node:
    image: kasmweb/kali-rolling-desktop:1.16.0
    container_name: student-node
    ports:
      - "127.0.0.1:6901:6901"
    shm_size: '2gb'
    restart: unless-stopped
    environment:
      - VNC_PW=StudentSecure2026!
      - KASM_SVC_USER_PASSWORD=StudentSecure2026!
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - START_VGL=1
    devices:
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    group_add:
      - "987"
      - "video"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
    - isolated-range
    - frontend-net
  # عقدة الدكتور / المشرف
  doctor-node:
    image: kasmweb/kali-rolling-desktop:1.16.0
    container_name: doctor-node
    environment:
      - VNC_PW=DoctorSecure2026!
      - KASM_SVC_USER_PASSWORD=DoctorSecure2026!
    volumes:
      - ./labs:/opt/range-labs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - isolated-range

  # مثال على هدف تدريبي معزول ينزله الدكتور (DVWA)
  target-dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: target-dvwa
    networks:
      - isolated-range
    profiles:
      - labs

networks:
  frontend-net:
    driver: bridge
  isolated-range:
    driver: bridge
    internal: true
